# Dockerfile production
# Use a base image with Node.js

# Stage 1: Build the application 
FROM node:20-alpine AS builder 

COPY package*.json ./

RUN npm ci --only=production

COPY . .

EXPOSE 5000

CMD ["npm", "start"]